In [1]:
import torch
import numpy as np

In [2]:
def load_feat_float(path, dims):
    return np.fromfile(path, dtype=np.float32).reshape(dims)

def save_feat_float(path, feat):
    feat.tofile(path)
    
def load_feat_int32(path, dims):
    return np.fromfile(path, dtype=np.int32).reshape(dims)

def save_feat_int32(path, feat):
    feat.tofile(path)

In [22]:
volum = load_feat_float('./ground_truth/volume_data.bin', (6, 200, 200, 12, 64))
volum_sum = volum.sum(0, keepdims=True)

In [37]:
# save_feat_float('./ground_truth/volume_sum_data.bin', volum_sum)
load_feat_int32('./input/n_voxels_data.bin', (3))

array([200, 200,  12], dtype=int32)

In [110]:
save_feat_int32('./input/n_voxels_data_128_128_6.bin', np.array([128, 128, 6], dtype=np.int32))

In [102]:
save_feat_int32('./input/n_voxels_data_128_128_12.bin', np.array([128, 128, 12], dtype=np.int32))

In [106]:
save_feat_int32('./input/n_voxels_data_256_256_6.bin', np.array([256, 256, 6], dtype=np.int32))

In [109]:
save_feat_int32('./input/n_voxels_data_256_256_12.bin', np.array([256, 256, 12], dtype=np.int32))

In [47]:
save_feat_int32('./input/n_voxels_data_64_64_12.bin', np.array([64, 64, 12], dtype=np.int32))

In [ ]:
save_feat_int32('./input/n_voxels_data_256_256_1.bin', np.array([256, 256, 1], dtype=np.int32))

In [51]:
load_feat_float('./input/voxel_size_data.bin', (3))

array([0.5, 0.5, 0.5], dtype=float32)

In [42]:
load_feat_float('./input/origin_data.bin', (3))

array([ 0.,  0., -1.], dtype=float32)

In [40]:
save_feat_float('./input/voxel_size_data_05_05_3.bin', np.array([0.5, 0.5, 3], dtype=np.float32))

In [35]:
save_feat_float('./input/voxel_size_data_05_05_6.bin', np.array([0.5, 0.5, 6], dtype=np.float32))

In [39]:
save_feat_float('./input/voxel_size_data_05_05_1.bin', np.array([0.5, 0.5, 1.0], dtype=np.float32))

In [41]:
save_feat_float('./input/voxel_size_data_05_05_025.bin', np.array([0.5, 0.5, 0.25], dtype=np.float32))

In [43]:
save_feat_float('./input/voxel_size_data_05_05_019.bin', np.array([0.5, 0.5, 0.19], dtype=np.float32))

In [45]:
save_feat_float('./input/voxel_size_data_05_05_005.bin', np.array([0.5, 0.5, 0.1], dtype=np.float32))

In [50]:
save_feat_float('./input/voxel_size_data_1_1_05.bin', np.array([1.0, 1.0, 0.5], dtype=np.float32))

In [104]:
save_feat_float('./input/voxel_size_data_078_078_1.bin', np.array([100/128, 100/128, 1.0], dtype=np.float32))

In [107]:
save_feat_float('./input/voxel_size_data_078_078_05.bin', np.array([100/128, 100/128, 0.5], dtype=np.float32))

In [105]:
save_feat_float('./input/voxel_size_data_039_039_1.bin', np.array([100/256, 100/256, 1.0], dtype=np.float32))

In [108]:
save_feat_float('./input/voxel_size_data_039_039_05.bin', np.array([100/256, 100/256, 0.5], dtype=np.float32))

# feature

In [ ]:
save_feat_float('./input/features_data_6_16_44_64.bin', np.random.randn(6, 16, 44, 64).astype(np.float32))

In [99]:
save_feat_float('./input/features_data_6_32_88_64.bin', np.random.randn(6, 32, 88, 64).astype(np.float32))

In [3]:
save_feat_float('./input/features_data_6_40_110_64.bin', np.random.randn(6, 40, 110, 64).astype(np.float32))

# project

In [90]:
load_feat_float('./input/projection_data.bin', (6, 3, 4))

array([[[ 7.6121468e+01, -3.6586349e+02, -1.5047620e+01, -6.2821236e+01],
        [ 1.1526153e+02, -3.2093849e+01, -3.1706943e+02, -1.4543939e+02],
        [ 9.3410861e-01, -3.5645434e-01, -1.9529385e-02, -4.7654495e-01]],

       [[ 1.2946361e+01,  3.7904681e+02,  8.9906530e+00, -1.0909841e+02],
        [-9.7573135e+01,  7.6232834e+01, -3.1665793e+02, -1.7584586e+02],
        [-8.1953663e-01,  5.7290763e-01,  1.1688368e-02, -5.7950824e-01]],

       [[ 3.4234146e+02, -1.5135385e+02, -7.3249741e+00, -1.0673708e+02],
        [ 9.9888046e+01,  7.5892685e+01, -3.1457266e+02, -1.8689586e+02],
        [ 8.3403468e-01,  5.5169547e-01,  4.2792447e-03, -6.4982831e-01]],

       [[-2.0325552e+02, -2.0634384e+02, -3.4848785e+00, -2.0562627e+02],
        [ 1.4010608e+00, -1.1895422e+02, -2.0318033e+02, -1.7548462e+02],
        [-4.6402640e-03, -9.9996191e-01, -7.3895603e-03, -9.8954087e-01]],

       [[ 3.1587366e+02,  2.0511452e+02,  5.7780108e+00, -1.0334457e+02],
        [ 1.5828595e+00,  1.28

In [96]:
projection = load_feat_float('./input/projection_data.bin', (6, 3, 4))
projection[:,:1,:] = projection[:,:1,:]*44/400
projection[:,1:2,:] = projection[:,1:2,:]*16/255
save_feat_float('./input/projection_data_d16_44.bin', projection)

In [97]:
projection = load_feat_float('./input/projection_data.bin', (6, 3, 4))
projection[:,:1,:] = projection[:,:1,:]*88/400
projection[:,1:2,:] = projection[:,1:2,:]*32/255
save_feat_float('./input/projection_data_d32_88.bin', projection)

In [4]:
projection = load_feat_float('./input/projection_data.bin', (6, 3, 4))
projection[:,:1,:] = projection[:,:1,:]*110/400
projection[:,1:2,:] = projection[:,1:2,:]*40/255
save_feat_float('./input/projection_data_d40_110.bin', projection)